[build]
  publish = "."
  
[[redirects]]
  from = "/1_1"
  to = "/1_1/Exp1_1.html"
  status = 200

[[redirects]]
  from = "/1_2"
  to = "/1_2/Exp1_2.html"
  status = 200

[[redirects]]
  from = "/1_3"
  to = "/1_3/Exp1_3.html"
  status = 200




