[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/Exp1_1/1_1.html"
  status = 200

[[redirects]]
  from = "/Exp1_1"
  to = "/Exp1_1/1_1.html"
  status = 200

[[redirects]]
  from = "/Exp1_2"
  to = "/Exp1_2/1_2.html"
  status = 200

[[redirects]]
  from = "/Exp1_3"
  to = "/Exp1_3/1_3.html"
  status = 200

